Add home page
Hector096/FirstRepo pull request #3
Opened 2021-08-10 14:40 UTC by Hector096

1: Added Home Page with a heading.
2: Added gitignore file.
3: Added linters to github/workflows

2021-08-10 15:11 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @Hector096 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
Changes required :writing_hand:  

 * #### Please check the comments under the review too
     
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-10 15:11 UTC, Emmyn5600 commented on .github/workflows/linters.yml
> +        run: npx stylelint "**/*.{css,scss}"
Nice you have included the linters.yml file properly, however there are missing some files in the configuration: for more details check this [template](https://github.com/microverseinc/linters-config/tree/master/html-css)

- .hintrc

- .stylelintrc.json

2021-08-10 15:11 UTC, Emmyn5600 commented on styles.css
> +}
- [ ] Please add the .gitignore file to keep the following:

- node_modules
- test.md

2021-08-11 09:39 UTC, AshakaE approved these changes
### Hi @Hector096  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 10:34 UTC, merged